### ISSUE TITLE
HTML5 boilerplate doesnt work  with django extension!

### ISSUE THREAD

**Issue by definite2** [sidthesloth92/vsc_html5_boilerplate#11]
When i first download it, it was working. When i added 
django, django template  extensions, it didn't work. I uninstalled them reload the VS code, then Boilerplate started to work:/

**Comment by borasavkar** [comment]
i have the same issue too

**Comment by stavrinoua** [comment]
same here :(

**Comment by benninkcorien** [comment]
Same.

Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by tusharkwagh99** [comment]
I have the same issue with Django Extention

**Comment by abdullah-al-rafi** [comment]
So, it's been here for a long time. Did any of you get a solution to use both the django extension and html files?

**Comment by cobriensr** [comment]
> 
> 
> So, it's been here for a long time. Did any of you get a solution to use both the django extension and html files?

Change the file type in vs code to HTML in the command palette was the only fix I found

**Comment by abdullah-al-rafi** [comment]
> > So, it's been here for a long time. Did any of you get a solution to use both the django extension and html files?
> 
> Change the file type in vs code to HTML in the command palette was the only fix I found

Hey! Why didn't I think of that? Thank you!!!

**Comment by sidthesloth92** [comment]
Fixed in 1.1.0
