### ISSUE TITLE
Not getting auto generation

### ISSUE THREAD

**Issue by suravarapusuryakiran** [sidthesloth92/vsc_html5_boilerplate#13]
Hi Team, 

I'm a new bee to visual studio and trying to do HTML. I installed plugin even after I couldn't get auto-detection? my boilerplate is enabled in visual studio file extension is also ends with .html.

**Comment by KringleClaus** [comment]
You likely have to download an auto-complete extension too.  E.g.: "auto complete tag"

**Comment by sidthesloth92** [comment]
Please make sure the file extension in the bottom right corner says 'HTML'. If not, you can click on it and see it to HTML and then it should work.

<img width="376" alt="Screenshot 2020-09-28 at 13 54 53" src="https://user-images.githubusercontent.com/4656109/94408376-56520180-0192-11eb-9b7f-dcd751dd15ef.png">
