### ISSUE TITLE
After installation, completion not being offered

### ISSUE THREAD

**Issue by sunilw** [sidthesloth92/vsc_html5_boilerplate#15]
I'm using a freshly installed version of VSC: 1.41.1 on linux.

After installing the extension and restarting VSC, completion for the boilerplate is not being offered.

I open a new file, save it with an .html suffix and start typing 'html5-boilerplate'.
Emmet completions are offered for the string 'html', but nothing is offered for 'html5-boilerplate'.

**Comment by sidthesloth92** [comment]
Please make sure the file extension in the bottom right corner says 'HTML'. If not, you can click on it and see it to HTML and then it should work.

<img width="376" alt="Screenshot 2020-09-28 at 13 54 53" src="https://user-images.githubusercontent.com/4656109/94408376-56520180-0192-11eb-9b7f-dcd751dd15ef.png">
