### ISSUE TITLE
not working..

### ISSUE THREAD

**Issue by rfx-ram** [sidthesloth92/vsc_html5_boilerplate#18]
Issue Type: <b>Bug</b>

even it showing anything. it  is looking like notepad. waste of time. 

Extension version: 1.0.3
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sidthesloth92** [comment]
Please make sure the file extension in the bottom right corner says 'HTML'. If not, you can click on it and see it to HTML and then it should work.

<img width="376" alt="Screenshot 2020-09-28 at 13 54 53" src="https://user-images.githubusercontent.com/4656109/94408376-56520180-0192-11eb-9b7f-dcd751dd15ef.png">
