### ISSUE TITLE
Nothing is happening....

### ISSUE THREAD

**Issue by Rainbow-Ninja** [sidthesloth92/vsc_html5_boilerplate#19]
I've installed it, loaded it, reloaded - everything you've said and I'm getting zip. i have this installed on my other lappy and it works just fine. I don't know if this is an update or what but it isn't working :/

**Comment by Praveer1981** [comment]
its not workig for me as well

**Comment by Guenyo** [comment]
Same for me :(

**Comment by sidthesloth92** [comment]
Please make sure the file extension in the bottom right corner says 'HTML'. If not, you can click on it and see it to HTML and then it should work.

<img width="376" alt="Screenshot 2020-09-28 at 13 54 53" src="https://user-images.githubusercontent.com/4656109/94408376-56520180-0192-11eb-9b7f-dcd751dd15ef.png">
