### ISSUE TITLE
Can't set custom templates?

### ISSUE THREAD

**Issue by isnomo** [sidthesloth92/vsc_html5_boilerplate#2]
I think it would be better if the user could set custom templates!

**Comment by libitya** [comment]
I agree with the questioner..

**Comment by rura6502** [comment]
you can change template. you can find template file in the %USERPROFILE%.vscode\extension\PLUGIN_FOLDER\snippets.
and need to restart vscode after change.

**Comment by sidthesloth92** [comment]
- Press Cmd + Shift + P in VS Code and type in Open Extensions folder.
- Navigate to /sidthesloth.html5-boilerplate-1.x.x/snippets
- Modify the template to your liking and restart VS Code
