### ISSUE TITLE
Html tag is never opened.

### ISSUE THREAD

**Issue by GillesVanPellicom** [sidthesloth92/vsc_html5_boilerplate#21]
<DOCTYPE html>

 <html class="no-js"> 
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
        
        <script src="" async defer></script>
    </body>
</html>
this is what is generated (you can't see most of it because apperantly github does not know how to handle text in a safe manner. I see a &lt/html&gt tag but no &lthtml&gt. This is extremely annoying because even though it works without the tag, some extension i use wont work unless  there is an html-head-body structure. I manage to keep forgetting this and spend +-15min every time a problem like this occurs troubleshooting. I've had this happen with 5 extensions now. Please resolve this simple issue

**Comment by sidthesloth92** [comment]
The extension does have an `html` tag in the first line: `<!DOCTYPE html>`.

**Comment by sidthesloth92** [comment]
Closed by https://github.com/sidthesloth92/vsc_html5_boilerplate/pull/23
