### ISSUE TITLE
Use boilerplate on a php file

### ISSUE THREAD

**Issue by PaulMur** [sidthesloth92/vsc_html5_boilerplate#4]
I have an issue where you cannot run the html5-boilerplate command on a PHP file, it would be nice to still utilize the boilerplate on a PHP file even tho it's a completely separate file type. 

If it's me being a doofus let me know and I can fix any local issues on my end.

Thanks

**Comment by PaulMur** [comment]
I shall add that the file I am working on is part of the blade templating engine

**Comment by AlexeyKot** [comment]
Have the same question about .hjtml.erb files, when I work on Ruby on Rails projects.
Can you expand this extension to work with more languages, rathen then only HTML, please?

**Comment by sidthesloth92** [comment]
Have included the ability to add the boilerplate to PHP and Ruby as a part of version 1.3.0. Do check it out and thanks for the feedback. Much appreciated...👍
