### ISSUE TITLE
Custom Boilerplate

### ISSUE THREAD

**Issue by kit-solent** [sidthesloth92/vsc_html5_boilerplate#46]
How could I customise the boilerplate code to better suit my needs?

**Comment by dtiessen95** [comment]
On Windows by changing the content of:
.vscode\extensions\sidthesloth.html5-boilerplate-1.1.1\snippets.json

**Comment by kit-solent** [comment]
Thanks

**Comment by sidthesloth92** [comment]
Thanks for the help @kit-solent
