### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by krsiakdaniel** [sidthesloth92/vsc_html5_boilerplate#5]
Hi there, nice little extension. 
Is it meant to be simple or is it now outdated?

See here is what I did (test) = your extension vs. latest boilerplate (index): http://recordit.co/PSElR5EYS8

**Comment by sidthesloth92** [comment]
I wouldn't say it is outdated. I just preferred leaving the selection of libraries to the users themselves, thus avoiding clutter. Having said that, I've included basic CSS and Script inclusion as a part of version 1.3.0. Do check it out and thanks for the feedback. Much appreciated...👍
