### ISSUE TITLE
HTML5 Bolierplate

### ISSUE THREAD

**Issue by Kathy145** [sidthesloth92/vsc_html5_boilerplate#6]
Hi!  Thank you for your efforts and the handy shortcut.  If there was a way to add standard CSS link to the boilerplate would be very helpful. <link href="style.css" rel="stylesheet" type="text/css">

Thanks in advance

**Comment by sidthesloth92** [comment]
Have added this as a part of version 1.3.0. Do check it out. Thanks for the feedback. Much appreciated...👍
