### ISSUE TITLE
html does nothing after install and reload

### ISSUE THREAD

**Issue by mccreeker** [sidthesloth92/vsc_html5_boilerplate#7]
I just followed the installation instructions here: https://marketplace.visualstudio.com/items?itemName=sidthesloth.html5-boilerplate

I click the green Reload button, VS Code reloads, I open a new file, type html, and nothing happens. I try html5 and hit Ctrl+Space, says no suggestions. I copy-paste html5-boilerplate and nothing happens. I paste 'html5-boilerplate' and nothing happens.

How is this thing supposed to work?

**Comment by francorona** [comment]
I have the same problem. It does nothing.

**Comment by francorona** [comment]
I didn't work when I typed `htmlboiler` either....

**Comment by sidthesloth92** [comment]
@mccreeker  @isaacalves  @francorona Can you provide more information? OS Version, VS Code version, stuff like that?  I just installed a new version of VS Code, installed the extension from the marketplace and it worked just fine. Do refer the updated GIF from the Readme. Hope this helps. And let me know if the issue persists.

**Comment by francorona** [comment]
I actually switched to using Atom instead of VS Code. Thanks though. My OS is Windows 10 and was the most recent version of VS Code.

**Comment by jep** [comment]
I noticed I had this issue initially. It turned out that the file you're working on must be saved as a .html file, instead of the default Untitled-1, before the `html` shows the boilerplate selection.

**Comment by sidthesloth92** [comment]
@jep Yes, the file needs to be saved with an extension for the snippet to show. Thanks for sharing the info.

**Comment by Jvalal** [comment]
didn't work for me. my file is "index.html" and nothing comes up when I type html...

**Comment by AVDW** [comment]
I had the same problem but found that vscode set the default language for html to Nunjucks. Changing the language back to html in the bottom corner made this extension work again.

![image](https://user-images.githubusercontent.com/5676238/49713907-74d1ca80-fc96-11e8-89cc-3ec70a9f3a19.png)

**Comment by bingoabs** [comment]
My OS is `Mac Darwin osx.10.12-x64`  and VS code version is `1.30.1`.

I found similar situation like @AVDW : 
![image](https://user-images.githubusercontent.com/15336985/50534460-f02cea80-0b77-11e9-8238-004c2939af53.png)
And the extension will work normal when manual change to HTML .
It is weird why the VS code treat my new html file as Django HTML in C# project folder...

**Comment by skorasaurus** [comment]
I had the same issue as well and only was able to get it to work after applying all of the following: 

- restarting vs code after installation
- [save an empty file as test.html](https://github.com/sidthesloth92/vsc_html5_boilerplate/issues/7#issuecomment-394082914)
- [set the language to HTML](https://github.com/sidthesloth92/vsc_html5_boilerplate/issues/7#issuecomment-445700293)

For those still unable to get it to work; make sure that you type "html" in the file editor; _not in the command palette_ (this initially tripped me up ;))

**Comment by ruffyleaf** [comment]
So to change Language Mode, there's a keyboard shortcut. Have a look [here](https://code.visualstudio.com/docs/getstarted/keybindings). For Mac, it's Cmd+K then M. It will open the command palette and then you select HTML. vice versa to switch back to your other language mode.

**Comment by LitoJamero** [comment]
> I had the same problem but found that vscode set the default language for html to Nunjucks. Changing the language back to html in the bottom corner made this extension work again.
> 
> ![image](https://user-images.githubusercontent.com/5676238/49713907-74d1ca80-fc96-11e8-89cc-3ec70a9f3a19.png)

Yes. This is the working solution for me.

**Comment by Gauthamanil7172** [comment]
initially, I had the same problem too then I tried disabling Django extension then it worked fine for me for some reason these two extensions don't work together

**Comment by rjmusic** [comment]
Same issue, worked after swapping from "Django HTML" to "HTML"

**Comment by Coding-Crowd** [comment]
> I had the same problem but found that vscode set the default language for html to Nunjucks. Changing the language back to html in the bottom corner made this extension work again.
> 
> ![image](https://user-images.githubusercontent.com/5676238/49713907-74d1ca80-fc96-11e8-89cc-3ec70a9f3a19.png)

Wow this helped thanks for sharing man great work
