### ISSUE TITLE
New Templates

### ISSUE THREAD

**Issue by shaunericson** [sidthesloth92/vsc_html5_boilerplate#9]
Hi, thanks for the awesome plug-in! Is there a way we can add our own templates?

**Comment by Christian-Stahl** [comment]
Or where to find the built in template, so we can modify it?

**Comment by jacobashymo** [comment]
I've been looking into this as well. Can't find anything.

**Comment by jdb5523** [comment]
Navigate to the extension installation folder (~/.vscode/extensions/sidthesloth.html5-boilerplate-x.x.x on Linux).

Inside the snippets folder, there is the html.json file which you can edit to match your desired template.

**Comment by myjoshem** [comment]
Here is the file in Windows. I could not find the file in the user settings under extensions, and my html.json does not have the boilerplate text I wish to edit.

C:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html\snippets\html.snippets.json

[html.snippets.zip](https://github.com/sidthesloth92/vsc_html5_boilerplate/files/2868197/html.snippets.zip)

**Comment by SirTwsted** [comment]
I would love to modify the boilerplate as well.
I also cant seem to find it,  ive been hammering my computer with the search function.
it cant find anything related to the boilerplate  :(
